### ISSUE TITLE
feature suggestion: computer program screen dimensions

### ISSUE THREAD

**Issue by raould** [fponticelli/thx.unit#4]
thanks for making this library! 

it might be cool to have computer units for x, y, width, height. That way we can be sure not to mix up x vs. y, they get type checked as being different. (I'd hope for that, anyway.) They could be unitless, or one could just have a "pixels" type?

If there's a pixels type, i'd also like there to be some kind of non-pixel type for when I'm making a virtual space that gets mapped onto the screen (imagine using vector graphics in some aribitrary space and then it just gets squashed to fit whatever screen it is running on). So maybe that would be virtualpixels or something, dunno what that name should be, exactly.

**Comment by fponticelli** [comment]
I can see a Pixel unit even if it will feel pretty solitary in a world with just one unit. The idea to add conversions to EM, PT or other relative measures would be cool but I am not sure how is the best way to implement it.
I feel less confident with  the x,y,width,height specific ones. I don't think they would add much value to code.

**Comment by fponticelli** [comment]
I added PT because it is an absolute measure. Relative measure are not a fit right now and would require a completely different treatment.
